spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: tuanworks280699@gmail.com
    password: bvzfwoigwlbwpdrb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
      test-connection: false
      protocol : smtp